# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_world": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://dustinbleile.github.io/fleet_gene/"

git_url = "https://github.com/dustinbleile/fleet_gene/tree/master/"

def custom_doc_links(name): return None
