# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['hello_world']

# Cell

def hello_world():
    """Simple hello world test"""
    # "only 'conda -c fastai' with all updates channel install worked.
    # pip install gave errors during nbdev_build_docs" - using ubuntu 20.04LTS on windows 10 wsl2.
    print(f"hello world test")