# AUTOGENERATED! DO NOT EDIT! File to edit: 01_GTEx.ipynb (unless otherwise specified).

__all__ = ['GTEX_URL', 'GTEXV8_TPM', 'GTEXV8_TPM_MED', 'GTEX_PHENO_DS', 'GTEX_PHENO_DD', 'GTEX_SAMPLE_DS',
           'GTEX_SAMPLE_DD']

# Cell
# export
# GTEx data from https://gtexportal.org/home/datasets
# Gene transcripts per million data

import os
# Open a handle onto the GTEx expression data
GTEX_URL =  "https://storage.googleapis.com/gtex_analysis_v8"
GTEXV8_TPM = os.path.join(GTEX_URL, "rna_seq_data", "GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz")
GTEXV8_TPM_MED = os.path.join(GTEX_URL, "rna_seq_data", "GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct.gz")
GTEX_PHENO_DS = os.path.join(GTEX_URL, "annotations", "GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt")
GTEX_PHENO_DD = os.path.join(GTEX_URL, "annotations", "GTEx_Analysis_v8_Annotations_SubjectPhenotypesDD.xlsx")
GTEX_SAMPLE_DS = os.path.join(GTEX_URL, "annotations", "GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")
GTEX_SAMPLE_DD = os.path.join(GTEX_URL, "annotations", "GTEx_Analysis_v8_Annotations_SampleAttributesDD.xlsx")